services:
  db:
    image: postgres:16
    container_name: money-transfer-db
    environment:
      POSTGRES_USER: money_user
      POSTGRES_PASSWORD: money_password
      POSTGRES_DB: money_transfer
    ports:
      - "5434:5432"   
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U money_user -d money_transfer"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: