"""add transaction and transfer indexes

Revision ID: 2481e872344e
Revises: df3f2dc600a4
Create Date: 2026-09-30 08:07:56.019463

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '2481e872344e'
down_revision: str | Sequence[str] | None = 'df3f2dc600a4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
