"""add transaction and transfer indexes

Revision ID: df3f2dc600a4
Revises: 33a8f8d3f9f7
Create Date: 2026-09-30 07:57:38.892772

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'df3f2dc600a4'
down_revision: str | Sequence[str] | None = '33a8f8d3f9f7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_created_at'), 'transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_transfers_destination_account_id'), 'transfers', ['destination_account_id'], unique=False)
    op.create_index(op.f('ix_transfers_source_account_id'), 'transfers', ['source_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfers_source_account_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_destination_account_id'), table_name='transfers')
    op.drop_index(op.f('ix_transactions_created_at'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    # ### end Alembic commands ###
